### ISSUE TITLE
Styledocco with scss not working on windows

### ISSUE THREAD

**Issue by escapedcat** [jacobrask/styledocco#121]
I have the following setup:

``` bash
node --version
v0.10.28
```

``` bash
styledocco --version
StyleDocco 0.6.6
```

``` bash
ruby --version
ruby 2.0.0p481 (2014-05-08) [x64-mingw32]
```

``` bash
sass --version
Sass 3.3.7 (Maptastic Maple)
```

In a folder I have...
`test-scss.scss`:

``` css
/* Provides extra visual weight and identifies the primary action in a set of buttons.

    <button class="btn primary">Primary</button> */
.btn.primary {
  background: deeppink;
  color: blue;
  border: 5px solid aqua;
}
```

When doing `styledocco --verbose` I get:

``` cmd
spawn ENOENT
styledocco: writing test-scss.scss -> docs\test-scss.html
styledocco: writing C:\my\path\index -> docs\index.html
```

The result is, that the CSS is not applied in the docs.
The same thing works when using `.css`.
Also everything works on Linux.

Love the project by the way! It's a great help!
